// <auto-generated />
using System;
using Dropdown.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dropdown.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220402071904_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dropdown.Models.Country", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("c_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Dropdown.Models.Emp1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sur_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("c_id")
                        .HasColumnType("int");

                    b.Property<int?>("s_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("c_id");

                    b.HasIndex("s_id");

                    b.ToTable("emp1s");
                });

            modelBuilder.Entity("Dropdown.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("registrations");
                });

            modelBuilder.Entity("Dropdown.Models.State", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("countryc_id")
                        .HasColumnType("int");

                    b.Property<string>("s_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("s_id");

                    b.HasIndex("countryc_id");

                    b.ToTable("states");
                });

            modelBuilder.Entity("Dropdown.Models.Emp1", b =>
                {
                    b.HasOne("Dropdown.Models.Country", "c")
                        .WithMany()
                        .HasForeignKey("c_id");

                    b.HasOne("Dropdown.Models.State", "s")
                        .WithMany()
                        .HasForeignKey("s_id");

                    b.Navigation("c");

                    b.Navigation("s");
                });

            modelBuilder.Entity("Dropdown.Models.State", b =>
                {
                    b.HasOne("Dropdown.Models.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryc_id");

                    b.Navigation("country");
                });
#pragma warning restore 612, 618
        }
    }
}
